spring:
  application:
    name: booking-service

  config:
    import: ${configserver.import}
  cloud:
    config:
      import-check.enabled: false
      fail-fast: false

      request-connect-timeout: 5000
      request-read-timeout: 5000
      retry:
        max-attempts: 6
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      label: master

server:
  port: 8081


configserver:
  import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8089}